<section class="main-slider">

    <div style="position:relative;width:100%;height:auto;margin-top:0px;margin-bottom:0px" class="forcefullwidth_wrapper_tp_banner"><div class="tp-banner-container" style="left: 0px; position: absolute; width: 1263px; overflow: visible;">
        <div class="tp-banner revslider-initialised tp-simpleresponsive hovered" id="revslider-573" style="max-height: 620px; background-color: rgba(0, 0, 0, 0); background-image: none; height: 620px;">
            <ul class="tp-revslider-mainul" style="display: block; overflow: hidden; width: 100%; height: 100%; max-height: none;">

                <li data-transition="fade" data-slotamount="1" data-masterspeed="1000" data-thumb="images/main-slider/1.jpg" data-saveperformance="off" data-title="We are Awsome" class="tp-revslider-slidesli active-revslide" style="width: 100%; height: 100%; overflow: hidden; z-index: 18; visibility: hidden; opacity: 0;">
                    <div class="slotholder" style="width:100%;height:100%;" data-duration="undefined" data-zoomstart="undefined" data-zoomend="undefined" data-rotationstart="undefined" data-rotationend="undefined" data-ease="undefined" data-bgpositionend="undefined" data-bgposition="center center" data-kenburns="undefined" data-easeme="undefined" data-bgfit="cover" data-bgfitend="undefined" data-owidth="undefined" data-oheight="undefined"><div class="tp-bgimg defaultimg" data-lazyload="undefined" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat" data-lazydone="undefined" src="images/main-slider/1.jpg" data-src="images/main-slider/1.jpg" style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url(&quot;images/main-slider/1.jpg&quot;); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 0; visibility: hidden;"></div></div>

                    <div class="tp-caption lfb tp-resizeme start" data-x="left" data-hoffset="15" data-y="center" data-voffset="-40" data-speed="1500" data-start="500" data-easing="easeOutExpo" data-splitin="none" data-splitout="none" data-elementdelay="0.01" data-endelementdelay="0.3" data-endspeed="1200" data-endeasing="Power4.easeIn" style="z-index: 4; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 25px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px; left: 46.5px; top: 203px; visibility: visible; opacity: 0; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.00166, 0, 645, 0, 1);"><div class="big-title" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 25px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px;"><h2 class="" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 67px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 1px; font-size: 48px;">We are a group of young attorneys <br style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 67px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 1px; font-size: 48px;">Offering the best law service </h2></div></div>

                    <div class="tp-caption lfb tp-resizeme start" data-x="left" data-hoffset="15" data-y="center" data-voffset="80" data-speed="1500" data-start="1000" data-easing="easeOutExpo" data-splitin="none" data-splitout="none" data-elementdelay="0.01" data-endelementdelay="0.3" data-endspeed="1200" data-endeasing="Power4.easeIn" style="z-index: 4; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 25px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px; left: 46.5px; top: 370px; visibility: visible; opacity: 0; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.00166, 0, 645, 0, 1);"><div class="link-btn" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 25px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px;"><a href="#" class="btn-thm" style="transition: all 0.2s ease-out 0s; min-height: 0px; min-width: 0px; line-height: 40px; border-width: 0px; margin: 0px; padding: 0px 9px 0px 27px; letter-spacing: 0px; font-size: 14px;">MAKE AN APPOINTMENT <i class="fa fa-arrow-circle-right" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 28px; border-width: 0px; margin: 0px 0px 0px 20px; padding: 0px 7px 0px 15px; letter-spacing: 0px; font-size: 14px;"></i></a></div></div>


                </li>

                <li data-transition="slideup" data-slotamount="1" data-masterspeed="1000" data-thumb="images/main-slider/2.jpg" data-saveperformance="off" data-title="With Awsome Services" class="tp-revslider-slidesli active-revslide" style="width: 100%; height: 100%; overflow: hidden; z-index: 18; visibility: hidden; opacity: 0;">
                    <div class="slotholder" style="width:100%;height:100%;" data-duration="undefined" data-zoomstart="undefined" data-zoomend="undefined" data-rotationstart="undefined" data-rotationend="undefined" data-ease="undefined" data-bgpositionend="undefined" data-bgposition="center center" data-kenburns="undefined" data-easeme="undefined" data-bgfit="cover" data-bgfitend="undefined" data-owidth="undefined" data-oheight="undefined"><div class="tp-bgimg defaultimg" data-lazyload="undefined" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat" data-lazydone="undefined" src="images/main-slider/2.jpg" data-src="images/main-slider/2.jpg" style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url(&quot;images/main-slider/2.jpg&quot;); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit;"></div></div>

                    <div class="tp-caption lfb tp-resizeme start" data-x="right" data-hoffset="-15" data-y="center" data-voffset="-90" data-speed="1500" data-start="500" data-easing="easeOutExpo" data-splitin="none" data-splitout="none" data-elementdelay="0.01" data-endelementdelay="0.3" data-endspeed="1200" data-endeasing="Power4.easeIn" style="z-index: 4; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 25px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px; left: 825.5px; top: 195px; visibility: visible; opacity: 0; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.00166, 0, 645, 0, 1);"><div class="slide-text text-right" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 25px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 20px;"><p class="color-theme" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 40px; border-width: 0px; margin: 0px 0px 10px; padding: 0px; letter-spacing: 0px; font-size: 20px;">"We try to make the world a secure place to live"</p></div></div>

                    <div class="tp-caption lfb tp-resizeme start" data-x="right" data-hoffset="-15" data-y="center" data-voffset="0" data-speed="1500" data-start="1000" data-easing="easeOutExpo" data-splitin="none" data-splitout="none" data-elementdelay="0.01" data-endelementdelay="0.3" data-endspeed="1200" data-endeasing="Power4.easeIn" style="z-index: 4; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 25px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px; left: 595.5px; top: 243px; visibility: visible; opacity: 0; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.00166, 0, 645, 0, 1);"><div class="text-right" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 25px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px;"><h2 style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 67px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 1px; font-size: 48px;">We are a group of professional <br style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 67px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 1px; font-size: 48px;">laywers and attorneys</h2></div></div>

                    <div class="tp-caption lfb tp-resizeme start" data-x="right" data-hoffset="-15" data-y="center" data-voffset="120" data-speed="1500" data-start="1500" data-easing="easeOutExpo" data-splitin="none" data-splitout="none" data-elementdelay="0.01" data-endelementdelay="0.3" data-endspeed="1200" data-endeasing="Power4.easeIn" style="z-index: 4; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 25px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px; left: 996.5px; top: 410px; visibility: visible; opacity: 0; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.00166, 0, 645, 0, 1);"><div class="link-btn text-right" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 25px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px;"><a href="#" class="btn-thm" style="transition: all 0.2s ease-out 0s; min-height: 0px; min-width: 0px; line-height: 40px; border-width: 0px; margin: 0px; padding: 0px 9px 0px 27px; letter-spacing: 0px; font-size: 14px;">CHECK OUR SERVICES <i class="fa fa-arrow-circle-right" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 28px; border-width: 0px; margin: 0px 0px 0px 20px; padding: 0px 7px 0px 15px; letter-spacing: 0px; font-size: 14px;"></i></a></div></div>


                </li>

                <li data-transition="fade" data-slotamount="1" data-masterspeed="1000" data-thumb="images/main-slider/3.jpg" data-saveperformance="off" data-title="We are Awsome" class="tp-revslider-slidesli active-revslide current-sr-slide-visible" style="width: 100%; height: 100%; overflow: hidden; visibility: inherit; opacity: 1; z-index: 20;">
                    <div class="slotholder" style="width:100%;height:100%;" data-duration="undefined" data-zoomstart="undefined" data-zoomend="undefined" data-rotationstart="undefined" data-rotationend="undefined" data-ease="undefined" data-bgpositionend="undefined" data-bgposition="center top" data-kenburns="undefined" data-easeme="undefined" data-bgfit="cover" data-bgfitend="undefined" data-owidth="undefined" data-oheight="undefined"><div class="tp-bgimg defaultimg" data-lazyload="undefined" data-bgfit="cover" data-bgposition="center top" data-bgrepeat="no-repeat" data-lazydone="undefined" src="images/main-slider/3.jpg" data-src="images/main-slider/3.jpg" style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url(&quot;images/main-slider/3.jpg&quot;); background-size: cover; background-position: center top; width: 100%; height: 100%; opacity: 1; visibility: inherit;"></div></div>


                    <div class="tp-caption lfb tp-resizeme start" data-x="left" data-hoffset="15" data-y="center" data-voffset="-90" data-speed="1500" data-start="500" data-easing="easeOutExpo" data-splitin="none" data-splitout="none" data-elementdelay="0.01" data-endelementdelay="0.3" data-endspeed="1200" data-endeasing="Power4.easeIn" style="z-index: 4; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 25px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px; left: 46.5px; top: 195px; visibility: visible; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.0025, 0, 0, 0, 1);"><div class="slide-text" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 25px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 20px;"><p class="color-theme" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 40px; border-width: 0px; margin: 0px 0px 10px; padding: 0px; letter-spacing: 0px; font-size: 20px;">"We try to make the world a secure place to live"</p></div></div>

                    <div class="tp-caption lfb tp-resizeme start" data-x="left" data-hoffset="15" data-y="center" data-voffset="0" data-speed="1500" data-start="1000" data-easing="easeOutExpo" data-splitin="none" data-splitout="none" data-elementdelay="0.01" data-endelementdelay="0.3" data-endspeed="1200" data-endeasing="Power4.easeIn" style="z-index: 4; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 25px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px; left: 46.5px; top: 243px; visibility: visible; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.0025, 0, 0, 0, 1);"><div class="big-title" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 25px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px;"><h2 style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 67px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 1px; font-size: 48px;">We are a group of professional <br style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 67px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 1px; font-size: 48px;">laywers and attorneys</h2></div></div>

                    <div class="tp-caption lfb tp-resizeme start" data-x="left" data-hoffset="15" data-y="center" data-voffset="120" data-speed="1500" data-start="1500" data-easing="easeOutExpo" data-splitin="none" data-splitout="none" data-elementdelay="0.01" data-endelementdelay="0.3" data-endspeed="1200" data-endeasing="Power4.easeIn" style="z-index: 4; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 25px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px; left: 46.5px; top: 410px; visibility: visible; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.0025, 0, 0, 0, 1);"><div class="link-btn" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 25px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px;"><a href="#" class="btn-thm" style="transition: all 0.2s ease-out 0s; min-height: 0px; min-width: 0px; line-height: 40px; border-width: 0px; margin: 0px; padding: 0px 9px 0px 27px; letter-spacing: 0px; font-size: 14px;">MAKE AN APPOINTMENT <i class="fa fa-arrow-circle-right" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 28px; border-width: 0px; margin: 0px 0px 0px 20px; padding: 0px 7px 0px 15px; letter-spacing: 0px; font-size: 14px;"></i></a></div></div>

                </li>

            </ul>

            <div class="tp-bannertimer" style="width: 30.37%; visibility: visible; transform: translate3d(0px, 0px, 0px);"></div>
            <div class="tp-loader spinner4" style="display: none;"><div class="dot1"></div><div class="dot2"></div><div class="bounce1"></div><div class="bounce2"></div><div class="bounce3"></div></div></div>
        <div class="tp-bullets simplebullets preview4" style="bottom: 20px; left: 50%; margin-left: -27px;"><div class="bullet first"></div><div class="bullet"></div><div class="bullet last selected"></div><div class="tpclear"></div></div><div style="position: absolute; top: 309px; margin-top: -55px; left: 0px;" class="tp-leftarrow tparrows default preview4"><div class="tp-arr-allwrapper"><div class="tp-arr-iwrapper"><div class="tp-arr-imgholder" style="transform: matrix(1, 0, 0, 1, 0, 0); background-image: url(&quot;images/main-slider/2.jpg&quot;);"></div><div class="tp-arr-imgholder2" style="background-image: url(&quot;images/main-slider/2.jpg&quot;); transform: matrix(1, 0, 0, 1, 0, 0);"></div><div class="tp-arr-titleholder">With Awsome Services</div><div class="tp-arr-subtitleholder"></div></div></div></div><div style="position: absolute; top: 309px; margin-top: -55px; right: 0px;" class="tp-rightarrow tparrows default preview4 hashoveralready"><div class="tp-arr-allwrapper"><div class="tp-arr-iwrapper"><div class="tp-arr-imgholder" style="transform: matrix(1, 0, 0, 1, 0, 0); background-image: url(&quot;images/main-slider/1.jpg&quot;);"></div><div class="tp-arr-imgholder2" style="background-image: url(&quot;images/main-slider/1.jpg&quot;); transform: matrix(1, 0, 0, 1, 0, 0);"></div><div class="tp-arr-titleholder">We are Awsome</div><div class="tp-arr-subtitleholder"></div></div></div></div></div><div class="tp-fullwidth-forcer" style="width:100%;height:620px"></div></div>
</section>